### 07.	Accounts

  SELECT concat(`last_name`, `first_name`, char_length(`first_name`), 'Restaurant') AS `username`,
		 reverse(substring(`email`, 2, 12)) AS `password`
    FROM waiters
   WHERE (NOT `salary` IS NULL)
ORDER BY `password` DESC;



/* 
07.	Accounts
The waiters needs to have access to the new software, so they need personal accounts. 
Your task is to generate their usernames and passwords.
Write a query that returns: 
username and password for all waiters which are not fired (fired waiter is a waiter without salary). 
The username is generated by 
   their last name immediately followed by 
   their first name  followed by 
   the number of characters from first name and at the end 
   "Restaurant". 
   
   The password is their email starting from the 2nd character to the 13th character and then reversed.

Order by password in descending order.
Required Columns
•	username (last_name + first_name + characters count from first_name + "Restaurant")
•	password (starting from the 2nd character to the 13th character of their email and then reversed) 
Example
username	password
BroadisDrusy5Restaurant	wen@3sidaorb
GeeringBrandon7Restaurant	ssi@9gnireeg
LevinChristy7Restaurant	namys@2nivel
…	…
FulgerRaffarty8Restaurant	csid@6regluf

*/